### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by deemeetree** [medialab/manylines#76]
I'm trying to run manylines on my system, but get the following error when running npm install:

npm ERR! Error: No compatible version found: http-proxy@'^1.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.5.9","0.5.10","0.5.11","0.6.0","0.6.1","0.6.2","0.6.4","0.6.5","0.6.6","0.7.0","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.8.7","0.9.0","0.9.1","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","1.0.0","1.0.1","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.2.0","1.2.1","1.3.0","1.4.0","1.4.1","1.4.2","1.4.3","1.5.0","1.5.1","1.5.2","1.5.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)

**Comment by paulgirard** [comment]
No news from October 2014.
Let's consider this issue closed
