### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/manylines#81]
Mandatory:
- [x] Message informing to save url 
- [x] store the corpus url dans le local storage > afficher dans la home page
- [x] Check auto-save
- [x] Prevent publish if not saved

Later:
- [ ] New logo and favicon
- [ ] Delete views button
- [ ] Design widget dani
- [ ] Add image to static site
- [ ] Beta stamp

Done:
- [x] Write some info in the static homepage
- [x] Precise that we are expecting a gexf file
- [x] Sendmail (how to find your corpora)
- [x] 8 minimum colors
- [x] Url + iframe
- [x] Save form clarification

**Comment by danieleguido** [comment]
Design widget:
- [ ] integrate fullscreen function in tools
- [ ] current title should be aligned to next/previous titles
