### ISSUE TITLE
Upload didn’t work

### ISSUE THREAD

**Issue by bniemann** [medialab/manylines#83]
Hello

I installed manylines by following your installation orders and set couchbase mock true. I am able to access the local manylines in google chrome and firefox. Unfortunately uploads didn’t work. I only get the message "Processing graph" but nothing else happens. I tried a test.gexf (https://github.com/medialab/heatgraph/blob/master/test.gexf) from heatgraph and get following errormessage in chromes js-console:
Uncaught TypeError: Cannot read property 'clear' of null (sigma-v1.0.3-edge.js:7729)
sigma.renderers.webgl.clearsigma-v1.0.3-edge.js:7413 
sigma.renderers.webgl.rendersigma-v1.0.3-edge.js:606 
sigma.rendersigma-v1.0.3-edge.js:577 
sigma.refreshapp.hacks.js:273 
hacks.data.methoddomino-v1.3.7.min.js:2 
ydomino-v1.3.7.min.js:2 
udomino-v1.3.7.min.js:2 u
domino-v1.3.7.min.js:2 t
domino-v1.3.7.min.js:2 
n.dispatchEvent emitters.$.change.reader.onload (pane.upload.js:92)

Cloud you help to fix this?

**Comment by Yomguithereal** [comment]
Hello @bniemann, your issue seems to be related to sigma. It happens when your browser's webgl crashes and then fails silently. Can you try rebooting your browser and retry the upload and tell me whether it fixed your problem?

**Comment by bniemann** [comment]
Hi, the problem seems to be on my system. A college tried my installation on his system and it is running fine. Nevertheless thanks for your quick answer!
