### ISSUE TITLE
Can't start manylines after reset

### ISSUE THREAD

**Issue by bornakke** [medialab/manylines#87]
We had to reset the server and now manylines wouldn't start returning the following error. Any one who have an suggestions to as what can be the cause of this error?

Best regards
Tobias

> manylines@0.0.2 start /manylines
> nodejs bin/start.js

api    verbose - graph connection through the default bucket.
api    verbose - narrative connection through the default bucket.
api    verbose - space connection through the default bucket.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.exports.start (/manylines/server/api.js:106:35)
    at /manylines/bin/start.js:11:31
    at /manylines/server/buckets.js:62:5
    at /manylines/node_modules/async/lib/async.js:254:17
    at /manylines/node_modules/async/lib/async.js:157:25
    at /manylines/node_modules/async/lib/async.js:251:21
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by Yomguithereal** [comment]
One of the port used by manylines are already used by the server for something else. Try changing the ports in the configuration and you should be able to start again.

**Comment by bornakke** [comment]
Thank you - that solved it :+1:
